server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa001?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: UserProvider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
#配置显示给消费者的服务器端标识信息
ProviderVersion: UserProvider001:7.7.7Vzzzzzzzzzzzzzzzzz

